#SPDX-License-Identifier: MIT-0
---
# defaults file for heat_k8s_cluster
stack_name: "k8s-cluster"

image: "Ubuntu-24.04"
flavor_master: "ubuntu-k8s-2c-4g"
flavor_worker: "ubuntu-small"

keypair_name: "k8s-cluster-key-heat"
keypair_public_key_path: ""

network: "frontend-net"
security_groups:
  - "dev-frontend-secgroup"

# OpenStack NodePort exposure defaults
nodeport_range_start: 30000
nodeport_range_end: 32767
nodeport_remote_cidr: "0.0.0.0/0"

# REQUIRED now (master will always get a floating IP)
floatingip_network: "provider"

worker_count: 2

master_name: "k8s-master-01"
worker_name_prefix: "k8s-worker-"

# Network & SSH defaults
subnet: "frontend-subnet"
inventory_dest: "./hosts_k8s.ini"
k8s_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
k8s_ssh_extra_args: "-o PreferredAuthentications=password -o PubkeyAuthentication=no"
